### ISSUE TITLE
TypeError: Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by tjorim** [animate-css/animate.css#1056]
**Describe the bug** A clear and concise description of what the bug is.
```
error  in ./node_modules/animate.css/animate.css
TypeError: Cannot read property 'name' of undefined
```

**To Reproduce** Steps to reproduce the behavior:

1. yarn install
2. yarn run build
3. See error

**Expected behavior** A clear and concise description of what you expected to happen.
No errors

**Comment by Seaaaaaaa** [comment]
I had the same problem

**Comment by eltonmesquita** [comment]
Please provide more details on the problem. Which builds tools you're using, etc.

Next time please read and use the issue template provided and not just delete parts of it .

**Comment by ws-h-ono** [comment]
Having same issue with Parcel 1.12.4 with animate.css 4.0.0. (Node.js 12.16.3 on Linux)
The whole bundling process stops with this error.
This also happens with `animate.compat.css`.

I have,
`require('animate.css/animate.min.css')`
in the entry point script.

```
node_modules/animate.css/animate.min.css:undefined:undefined: Cannot read property 'name' of undefined
     at Object.<anonymous> (node_modules/animate.css/postcss.config.js:12:55)
     at Module._compile (node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
     at Module.load (internal/modules/cjs/loader.js:977:32)
     at Function.Module._load (internal/modules/cjs/loader.js:877:14)
     at Module.require (internal/modules/cjs/loader.js:1019:19)
     at require (node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
     at Object.load (node_modules/parcel-bundler/src/utils/config.js:40:22)
     at async getConfig (node_modules/parcel-bundler/src/transforms/postcss.js:25:16)
     at async module.exports (node_modules/parcel-bundler/src/transforms/postcss.js:11:16)
```

**Comment by eltonmesquita** [comment]
Thanks @ws-h-ono , I've got to reproduce it. I'm investigating the problem, should there be a fix soon.

**Comment by eltonmesquita** [comment]
Please, upgrade to the new version and check if it fixes the issue. I'd be glad if I had any feedback on this @tjorim, @Seaaaaaaa and @ws-h-ono

**Comment by tjorim** [comment]
It's working now, thank you so much.

**Comment by ws-h-ono** [comment]
Working now too, thank you.
